image: node:16.13.0-alpine

before_script:
  - npm i -g firebase-tools

deploy-functions:
  stage: deploy
  environment: Production
  script:
    - cd functions
    - npm install
    - cd ..
    - firebase use --token $FIREBASE_TOKEN electric-icon-175518
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --only functions --token $FIREBASE_TOKEN
  
  only:
    refs:
      - main
    changes:
      - functions/**/*