image: node:16.13.0-alpine

before_script:
  - npm i -g firebase-tools

deploy-functions:
  stage: deploy
  script:
    - cd functions
    - npm install
    - cd ..
    - firebase deploy --only functions --token $FIREBASE_TOKEN
  
  only:
    refs:
      - main
    changes:
      - functions/**/*